/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio1;

public class App {

    public static void main(String[] args) {
        
        Pessoa pessoa = new Pessoa("Edvaldo", 1.73f, 1994, 2022);
        
        System.out.print(pessoa.toString());
    }
}
